### ISSUE TITLE
Add Support for Showing All Results Organized By x

### ISSUE THREAD

**Issue by davidshq** [BraadMartin/plugin-cards#1]
Wondering if you would be able to add the ability to generate a list of all the plugins organized by x? In my instance, I'm looking to get all of the plugins ordered by downloads.

I tried something like this:

[plugin_cards max_results="999999" browse="popular"]

But that doesn't seem to work, it still gives me a finite number of results (not sure how many, 50, 100?).

**Comment by BraadMartin** [comment]
@davidshq I really wish this was possible, but the .org API currently has a hard limit on the number of plugins you can return at once. I haven't figured out exactly what it is yet, but I believe it is somewhere between 50 and 200.

When you make queries to the API, you set the 'per_page' argument just like you do with WP_Query, and then if you want results from page 2 you explicitly ask for page 2, and if your per_page was set to 10 then page 2 would give you results 11-20. I think if you take this approach and do your requests in batches you might be able to get every last plugin in the repo, but you should know that technically speaking the .org API that Plugin Cards uses is "not meant for public consumption" (according to core devs) which means if you build a service that relies on the API to get accurate information you might find the IP you're sending your requests from blocked after a certain number of large queries one after another (I wish this wasn't the case, but I've heard it said).

If I were you, I'd consider looking at the function plugins_api() which is included in core WordPress at /wp-admin/includes/plugin-install.php. This is the raw function that Plugin Cards uses to get information about plugins from the repo, and if you're building something custom you're probably best off calling that function directly, as it will return the raw plugin data rather than the rendered cards that Plugin Cards adds.

Since I can't get around the core limitation of the API in Plugin Cards, I'm going to close this issue for now, but feel free to ask any remaining questions you might have and I'll do my best to point you in the right direction, and thank you for using Plugin Cards!
